name: movies_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animated_splash_screen: ^1.2.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  dio_interceptors: ^0.0.4+1
  firebase: ^9.0.2
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.10
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_lints: ^1.0.4
  flutter_local_notifications: ^9.4.0
  flutter_riverpod: ^1.0.3
  flutter_staggered_animations: ^1.0.0
  get: ^4.6.1
  get_it: ^7.2.0
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
  riverpod: ^1.0.3
  shimmer: ^2.0.0

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
